<?php
/**
 * Wpopalipay Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Wpopalipay
 * @package	Wpopalipay_Payment
 * @copyright	Copyright (c) 2015 Wpopalipay (http://www.wpopalipay.com)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Wpopalipay_Payment
 * @author     Wpopalipay
 * @property   Wpopalipay Limited
 * @copyright  Copyright (c) 2015 Wpopalipay Limited (http://www.wpopalipay.com)
 */
?>

<img style="margin-right: 6px;" src="<?php echo $this->getPaymentMethodIcon(); ?>" alt="<?php echo $this->getPaymentMethodLabel() ?>" border="0"/>
